In [1]:
# 1. Criação de Arrays
# • Crie um array unidimensional com os números de 1 a 10 usando np.arange().
# • Redimensione o array para uma matriz 2x5.

import numpy as np

arr = np.arange(1, 11, 1)
print(arr)

new_arr = arr.reshape(2, 5)
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [2]:
# 2. Criação de Produtos
# • Crie um array com os preços de 10 produtos, variando de 5 a 50 euros, e transforme-o
# numa matriz 2x5 (2 categorias de produtos, cada uma com 5 preços).

precos = np.arange(5, 55, 5)
print(precos)
matriz_precos = precos.reshape(2, 5)
print(matriz_precos)

[ 5 10 15 20 25 30 35 40 45 50]
[[ 5 10 15 20 25]
 [30 35 40 45 50]]


In [3]:
"""3.Preenchimento do Inventário
• Crie uma matriz 3x4 que representa a quantidade de stock de 3 produtos em 4
armazéns. Preencha com o valor 100."""

produtos = np.full((3, 4), 100)
print(produtos)
#matriz_produtos = produtos.reshape(3, 4)
#print(matriz_produtos)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]


In [4]:
""""4. Transformação

• Crie uma matriz 4x5 com os custos dos produtos em diferentes fornecedores, criados
de forma aleatória e achate-a para um array unidimensional."""

matriz_custos = np.random.randint(0, 100, size=(4,5))
array_custos = matriz_custos.flatten()

print("Matriz de custos:\n", matriz_custos)
print("\nArray de custos:\n", array_custos)


Matriz de custos:
 [[13 88 85 67 80]
 [28 40 84 28 85]
 [80 99 66 13  1]
 [79 30 99  0 77]]

Array de custos:
 [13 88 85 67 80 28 40 84 28 85 80 99 66 13  1 79 30 99  0 77]


In [5]:
"""Operações Matemáticas e Estatísticas

5. Cálculo de Faturação
• Crie um array com o número de unidades vendidas para 5 produtos e outro com os
seus preços. Calcule a faturação total de cada produto."""

unidades_vendidas = np.array([10, 5, 20, 8, 15])
precos = np.array([50, 120, 30, 80, 60])

faturacao_total = unidades_vendidas * precos

print("Faturação total:", faturacao_total)

Faturação total: [500 600 600 640 900]


In [6]:
precos_venda = np.array([60, 130, 40, 90, 70])
custos_producao = np.array([30, 80, 20, 50, 40])

lucro_unitario = precos_venda - custos_producao
print(lucro_unitario)

[30 50 20 40 30]


In [7]:
vendas_semanais = np.random.randint(50, 201, size=(4, 5))
vendas_totais = vendas_semanais.sum(axis=0)

produto_maior_venda = vendas_totais.argmax()

print("Vendas semanais:\n", vendas_semanais)
print("\nVendas totais por produto:\n", vendas_totais)
print("\nProduto com maior venda total:", produto_maior_venda + 1) 

Vendas semanais:
 [[105 147 179  92 128]
 [ 77 186 130 106 177]
 [123 184 132 197  51]
 [191 180  61 151 101]]

Vendas totais por produto:
 [496 697 502 546 457]

Produto com maior venda total: 2


In [8]:
array_aleatorio = np.random.randint(10, 51, size=20)

media = np.mean(array_aleatorio)
mediana = np.median(array_aleatorio)
variancia = np.var(array_aleatorio)
minimo = np.min(array_aleatorio)
maximo = np.max(array_aleatorio)
desvio_padrao = np.std(array_aleatorio)

print("Array aleatório:\n", array_aleatorio)
print("\nMédia:", media)
print("Mediana:", mediana)
print("Variância:", variancia)
print("Mínimo:", minimo)
print("Máximo:", maximo)
print("Desvio padrão:", desvio_padrao)

Array aleatório:
 [30 13 27 15 50 29 44 39 22 15 34 25 36 14 33 11 45 33 13 26]

Média: 27.7
Mediana: 28.0
Variância: 131.31
Mínimo: 11
Máximo: 50
Desvio padrão: 11.459057552870568


In [9]:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vetor = np.array([10, 20, 30])

matriz_com_broadcasting = matriz + vetor

print("Matriz original:\n", matriz)
print("\nVetor:\n", vetor)
print("\nMatriz com broadcasting:\n", matriz_com_broadcasting)

Matriz original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Vetor:
 [10 20 30]

Matriz com broadcasting:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [10]:
stocks = np.random.randint(10, 150, size=10)

produtos_baixo_stock = stocks[stocks < 50]

print("Stocks:\n", stocks)
print("\nProdutos com baixo stock:\n", produtos_baixo_stock)

Stocks:
 [110  49  35 121 102  95  84  22  19  96]

Produtos com baixo stock:
 [49 35 22 19]


In [11]:
precos = np.array([25, 35, 15, 40, 20, 50, 30, 60])

precos_com_desconto = np.where(precos > 30, precos * 0.8, precos)

print("Preços originais:\n", precos)
print("\nPreços com desconto:\n", precos_com_desconto)

Preços originais:
 [25 35 15 40 20 50 30 60]

Preços com desconto:
 [25. 28. 15. 32. 20. 40. 30. 48.]


In [12]:
stocks_atuais = np.random.randint(10, 150, size=6)

stocks_ajustados = np.clip(stocks_atuais, 20, 100)

print("Stocks atuais:\n", stocks_atuais)
print("\nStocks ajustados:\n", stocks_ajustados)

Stocks atuais:
 [ 33  14 130 138 131 108]

Stocks ajustados:
 [ 33  20 100 100 100 100]


In [13]:
import pandas as pd

df_filmes = pd.read_excel('Movies.xlsx')

filmes_bilionarios = df_filmes[df_filmes["Box Office"] > 1000000000]

df_filmes["High_Earnings"] = np.where(df_filmes["Box Office"] > 1000000000, "Yes", "No")

print("Filmes com Box Office superior a 1 bilhão:\n", filmes_bilionarios)
print("\nDataFrame com a coluna High_Earnings:\n", df_filmes)

Filmes com Box Office superior a 1 bilhão:
        ID                                          Title Release Date  \
0       1                                  Jurassic Park   1993-06-11   
4       6                                        Titanic   1998-01-23   
19     21     Pirates of the Caribbean: Dead Man's Chest   2006-07-06   
46     48      Star Wars: Episode I - The Phantom Menace   1999-05-19   
71     73      The Lord of the Rings: Return of the King   2003-12-17   
262   270                Transformers: Age of Extinction   2014-06-27   
272   280                                         Frozen   2013-11-27   
273   281                                     Iron Man 3   2013-05-03   
282   290                                   The Avengers   2012-05-04   
283   291                                        Skyfall   2012-10-26   
284   292                          The Dark Knight Rises   2012-07-20   
285   293              The Hobbit: An Unexpected Journey   2012-12-14   
292   3

In [14]:
df_filmes["Profit"] = df_filmes["Box Office"] - df_filmes["Budget"]

media_lucros = np.mean(df_filmes["Profit"])
desvio_padrao_lucros = np.std(df_filmes["Profit"])

print("Lucros dos filmes:\n", df_filmes["Profit"])
print("\nMédia dos lucros:", media_lucros)
print("Desvio padrão dos lucros:", desvio_padrao_lucros)

Lucros dos filmes:
 0       9.669399e+08
1       6.817086e+08
2       3.435000e+08
3       1.870812e+08
4       1.986772e+09
            ...     
1195    2.270000e+07
1196    7.300000e+07
1197   -1.670000e+07
1198    1.370000e+08
1199    1.398000e+08
Name: Profit, Length: 1200, dtype: float64

Média dos lucros: 185412561.8795411
Desvio padrão dos lucros: 247964265.59754825
