In [3]:
import numpy as np

vetor = np.array ([2,4,6,8,10])
print(vetor)

[ 2  4  6  8 10]


In [11]:
matriz = np.array ([[2, 4], [1, 3], [1 , 2]])
print(matriz)

[[2 4]
 [1 3]
 [1 2]]


In [13]:
intervalo = np.arange (0, 10, 2)
print(intervalo)

[0 2 4 6 8]
